fix(backend): salt can contain non convertable characters
leads to errors like this:
File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

because of that all bytes are converted to hex